version: '3.5'


services:
  iroutine-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iroutine_front
    ports:
      - '3000:3000'
    volumes:
    - .:/app
    - /app/node_modules